name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    env:
      ENVIRONMENT: ${{ secrets.ENVIRONMENT}}
      DOCKER_CA: ${{ secrets.DOCKER_CA}}
      DOCKER_CERT: ${{ secrets.DOCKER_CERT}}
      DOCKER_KEY: ${{ secrets.DOCKER_KEY}}
      HOST: ${{ secrets.HOST}}
      DOCKER_STACK: ${{ secrets.DOCKER_STACK }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: ./scripts/setup_ci.sh
    - name: Run Deploy
      run: ./scripts/deploy.sh
    - name: Clean
      if: always()
      run: ./scripts/tear_down_ci.sh
